name: campus170_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  audioplayers: ^5.2.1
  country_state_city: ^0.1.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.3.0
  flutter_bloc: ^8.1.3
  flutter_breadcrumb: ^1.0.1
  flutter_chat_bubble: ^2.0.2
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  http: ^1.1.0
  in_app_notification: ^1.1.2
  input_history_text_field: ^0.2.0
  intl: ^0.19.0
  keyboard_attachable: ^2.2.0
  loading_progress_indicator: ^0.1.6
  navigation_system: ^0.0.5
  percent_indicator: ^4.2.3
  pin_code_text_field: ^1.8.0
  smooth_page_indicator: ^1.1.0
  sticky_grouped_list: ^3.1.0
  url_launcher: ^6.2.1
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/icons/images/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight:  500
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight:  600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight:  700
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans/DMSans-Regular.ttf
        - asset: assets/fonts/DMSans/DMSans-Light.ttf
          weight:  500
        - asset: assets/fonts/DMSans/DMSans-Regular.ttf
          weight:  600
        - asset: assets/fonts/DMSans/DMSans-Bold.ttf
          weight:  700